from os.path import *
from os import chdir
import numpy as np
import pickle
import unittest

SAVE_RESULTS = True


class Tester(unittest.TestCase):

    def __init__(self, *args, **kwargs):
        super(Tester, self).__init__(*args, **kwargs)

        #   change directory to data filder
        self.data_dir = join(dirname(__file__), 'data')
        chdir(self.data_dir)

        #   override np.savetxt so we capture the raw data and prevent writing to disk
        self.savetxt_orig = np.savetxt
        self.file_data = {}
        self.ref_file_data = {}
        def savetxt_new(fname, X, **kwargs):
            self.file_data[fname] = X
        np.savetxt = savetxt_new

    def __del__(self):
        np.savetxt = self.savetxt_orig

    def check_files(self, name: str):
        '''
            Load the reference data files, and check that references file names
            have also been generated by the test. If SAVE_RESULTS = True, then
            this method will also save the files to disk BEFORE checking. This
            is usefull for generating new unit tests.

            Parameters
            ----------
            name : str
                The name of the test that is to be loaded and checked
        '''

        ref_file_loc = join('reference', name) + '.pkl'

        #   dump results, used to reset or update tests
        if SAVE_RESULTS:
            with open(ref_file_loc, 'wb') as file:
                pickle.dump(self.file_data, file)
        
        #   load reference data
        with open(ref_file_loc, 'rb') as file:
            self.ref_file_data = pickle.load(file)
        print("REF DATA: ", self.ref_file_data)

        #   make sure all file names were produced by molspecpy
        for file_name in self.file_data:
            assert file_name in self.ref_file_data

    def compare_spectra(self, spectrum_name: str):
        '''
            Compares linear spectrum array information, like absorption and emission

            Parameters
            ----------
            spectrum_name : str
                the suffix of the spectrum data file (i.e. 'MD_ensemble_spectrum.dat')
        '''
        #   grab data and make sure there is only one
        data = []
        ref_data = []
        for file, d in self.file_data.items():
            if spectrum_name in file:
                data.append(d)
                ref_data.append(self.ref_file_data[file])
        assert len(data) == 1

        data = data[0]
        ref_data = ref_data[0]

        #   make sure first and last energies are the same
        self.assertEqual(data[0, 0], ref_data[0, 0])
        self.assertEqual(data[-1, 0], ref_data[-1, 0])

        #   make sure intervals are the same at each end too
        dE_ref_first = ref_data[1, 0] - ref_data[0, 0]
        dE_ref_last = ref_data[-1, 0] - ref_data[-2, 0]
        dE_first = data[1, 0] - data[0, 0]
        dE_last = data[-1, 0] - data[-2, 0]
        self.assertEqual(dE_ref_first, dE_first)
        self.assertEqual(dE_ref_last, dE_last)
        self.assertEqual(dE_ref_first, dE_ref_last)
        self.assertEqual(dE_first, dE_last)

        #   no NaNs are allowed
        self.assertEqual(np.sum(np.isnan(data)), 0)

        #   now check actual spectrum data itself
        np.testing.assert_array_almost_equal(data, ref_data, 14, verbose=True)
